include:
  - project: 'ericvh/gitlab-ci-arm-template'
    file: '/.gitlab-ci.yml'

variables:
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm"


build:buildx-master:
  before_script:
    - cd build


build:buildx:
  before_script:
    - cd build
