include:
  - project: 'ericvh/gitlab-ci-arm-template'
    file: '/.gitlab-ci.yml'

variables:
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm"

build:buildx:
  script:
    - cd build
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx ls
    - docker buildx build --platform $CI_BUILDX_ARCHS --progress plain --pull -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" --push .
