apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: smarter-cni
  name: smarter-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: smarter-cni
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: smarter-cni
    spec:
      containers:
        command:
        - smarter-cni-run
        image: "smartercni:1.0"
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - "/smarter-cni-install.sh"
              - "--enable-debug=false"
          preStop:
            exec:
              command:
              - /smarter-cni-uninstall.sh
        name: smarter-cni-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        volumeMounts:
        - mountPath: /var/run/smartercni
          name: smartercni-run
        - mountPath: /host/opt/cni/bin
          name: cni-path
        - mountPath: /host/etc/cni/net.d
          name: etc-cni-netd
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      hostNetwork: true
      volumes:
        # To keep state between restarts / upgrades
      - hostPath:
          path: /var/run/smartercni
          type: DirectoryOrCreate
        name: smartercni-run	  
      # To install cni plugin in the host
      - hostPath:
          path:  /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-path
        # To install cni configuration in the host
      - hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate
        name: etc-cni-netd
        # To be able to load kernel modules
      - hostPath:
          path: /lib/modules
        name: lib-modules
        # To access iptables concurrently with other processes (e.g. kube-proxy)
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
---
