apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.configMapName }}
data:
  CIDR: "172.39.0.0/16"
  GW:   "172.39.0.1"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: {{ .Values.application.appName }}
  name: {{ .Values.application.appName }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.application.appName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.application.appName }}
    spec:
      nodeSelector:
        {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- else }}
        smarter.cni: enabled
        {{- end }}
      priorityClassName: "system-node-critical"
      tolerations:
        - key: "smarter.type"
          operator: "Equal"
          value: "edge"
          effect: "NoSchedule"
      containers:
        - name: {{ .Values.application.appName }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
          volumeMounts:
          - mountPath: /opt/cni
            name: cni-path
          - mountPath: /etc/cni
            name: etc-cni-netd
          - mountPath: /usr/libexec/cni
            name: alt-cni-path
          env:
          - name: DEST_DIR
            value: "/opt/cni/bin"
          envFrom:
          - configMapRef:
              name: {{ .Values.application.configMapName }}
      restartPolicy: Always
      priorityClassName: system-node-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
       - operator: Exists
         effect: NoSchedule
      volumes:
      # To install cni plugin in the host
      - hostPath:
          path:  /opt/cni
          type: DirectoryOrCreate
        name: cni-path
        # To install cni configuration in the host
      - hostPath:
          path: /etc/cni
          type: DirectoryOrCreate
        name: etc-cni-netd
      - hostPath:
          path:  /usr/libexec/cni
        name: alt-cni-path
---
